
version: '3.3'
services:

    web:
        build : ./
        container_name: webApi
        restart: always
        privileged: true
        sysctls:
          net.ipv4.ip_unprivileged_port_start: 0
        ports:
          - "9000:80"
        links:
          - db
        volumes:
          - ./:/var/www/src
        environment:
            ENABLE_ENV_FILE: 1

    db:
        image: postgres:10
        restart: always
        environment:
            POSTGRES_PASSWORD: api
            POSTGRES_DB: api
            POSTGRES_USER: api

    adminer:
        image: adminer
        restart: always
        ports:
          - 8090:8080
